-- MySQL Script generated by MySQL Workbench
-- Вт 08 дек 2020 23:22:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exams
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exams` ;

-- -----------------------------------------------------
-- Schema exams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exams` DEFAULT CHARACTER SET utf8 ;
USE `exams` ;

-- -----------------------------------------------------
-- Table `exams`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`subjects` (
  `idsubjects` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubjects`),
  UNIQUE INDEX `idsubjects_UNIQUE` (`idsubjects` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`students` (
  `idstudents` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `SUBJECT1` INT NOT NULL,
  PRIMARY KEY (`idstudents`),
  UNIQUE INDEX `idstudents_UNIQUE` (`idstudents` ASC) VISIBLE,
  INDEX `students_idx` (`SUBJECT1` ASC) VISIBLE,
  CONSTRAINT `students`
    FOREIGN KEY (`SUBJECT1`)
    REFERENCES `exams`.`subjects` (`idsubjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
